BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rugix-rpi-tryboot"
BBFILE_PATTERN_meta-rugix-rpi-tryboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rugix-rpi-tryboot = "10"

LAYERDEPENDS_meta-rugix-rpi-tryboot = "core meta-rugix-core"
LAYERRECOMMENDS_meta-rugix-rpi-tryboot = ""
LAYERSERIES_COMPAT_meta-rugix-rpi-tryboot = "wrynose"

WKS_FILE:rpi ?= "sdimage-rugix-rpi-tryboot.wks.in"
RUGIX_SLOTS:rpi ?= "boot:2 system:4"
IMAGE_INSTALL:append:rpi = "${@bb.utils.contains('DISTRO_FEATURES', 'rugix', ' packagegroup-rugix-bsp', '', d)}"
