BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rugix-qemu-arm64-uboot"
BBFILE_PATTERN_meta-rugix-qemu-arm64-uboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rugix-qemu-arm64-uboot = "10"

LAYERDEPENDS_meta-rugix-qemu-arm64-uboot = "core meta-rugix-core"
LAYERRECOMMENDS_meta-rugix-qemu-arm64-uboot = ""
LAYERSERIES_COMPAT_meta-rugix-qemu-arm64-uboot = "wrynose"

WKS_FILE:qemuarm64 ?= "qemu-arm64-rugix-uboot.wks"
WKS_FILE_DEPENDS:append:qemuarm64 = " u-boot-boot-image"
RUGIX_SLOTS:qemuarm64 ?= "system:2"
IMAGE_INSTALL:append:qemuarm64 = "${@bb.utils.contains('DISTRO_FEATURES', 'rugix', ' packagegroup-rugix-bsp', '', d)}"
