#:schema https://raw.githubusercontent.com/rugix/rugix/refs/tags/v1.3.0/schemas/rugix-ctrl-system.schema.json
[config-partition]
partition = 1
protected = true

[data-partition]
partition = 6

[boot-flow]
type = "uboot"

[boot-groups.a]
slots = { system = "system-a", boot = "boot-a" }

[boot-groups.b]
slots = { system = "system-b", boot = "boot-b" }

[slots.boot-a]
type = "block"
partition = 2
immutable = true

[slots.boot-b]
type = "block"
partition = 3
immutable = true

[slots.system-a]
type = "block"
partition = 4
immutable = true

[slots.system-b]
type = "block"
partition = 5
immutable = true
